language: "en"

pipeline:
- name: "SpacyNLP"
- name: "SpacyTokenizer"
- name: "RegexFeaturizer"
- name: "SpacyFeaturizer"
- name: "CRFEntityExtractor"
- name: "DucklingHTTPExtractor"
  url: "http://0.0.0.0:8000"
- name: "EntitySynonymMapper"
- name: "SklearnIntentClassifier"

policies:
  - name: KerasPolicy
    epochs: 50
    max_history: 6
  - name: MemoizationPolicy
    max_history: 6
  - name: FormPolicy
